/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>
#include <float.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#include "math.h"

START_TEST(test_abs) {
  ck_assert_int_eq(abs(1), abs(1));
  ck_assert_int_eq(abs(-1), abs(-1));
  ck_assert_int_eq(abs(0), abs(0));
  ck_assert_int_eq(abs(-0), abs(-0));
  ck_assert_int_eq(abs(123456), abs(123456));
  ck_assert_int_eq(abs(-123456), abs(-123456));
  ck_assert_int_eq(abs(123456 / 7), abs(123456 / 7));
  ck_assert_int_eq(abs(-123456 / 7), abs(-123456 / 7));
  ck_assert_int_eq(abs(INT_MIN), abs(INT_MIN));
  ck_assert_int_eq(abs(INT_MAX), abs(INT_MAX));
}
END_TEST

START_TEST(test_fmod) {
  ck_assert_ldouble_eq_tol(fmod(1, 1), fmod(1, 1), CH_EPS);
  ck_assert_ldouble_eq_tol(fmod(0, 1), fmod(0, 1), CH_EPS);
  ck_assert_ldouble_nan(fmod(1, 0));
  ck_assert_ldouble_nan(fmod(0, 0));
  ck_assert_ldouble_eq_tol(fmod(2.5, 1.1), fmod(2.5, 1.1), CH_EPS);
  ck_assert_ldouble_eq_tol(fmod(-2.5, 1.1), fmod(-2.5, 1.1), CH_EPS);
  ck_assert_ldouble_eq_tol(fmod(123456, 6.5), fmod(123456, 6.5), CH_EPS);
  ck_assert_ldouble_eq_tol(fmod(-0.01, 0.1), fmod(-0.01, 0.1), CH_EPS);
  ck_assert_ldouble_eq_tol(fmod(-0.01, 0.1), fmod(-0.01, 0.1), CH_EPS);
  ck_assert_ldouble_eq_tol(fmod(-0.01, CH_INF), fmod(-0.01, CH_INF),
                           CH_EPS);
  ck_assert_ldouble_eq_tol(fmod(-0.00000001, -0.000000001),
                           fmod(-0.00000001, -0.000000001), CH_EPS);
  ck_assert_ldouble_eq_tol(fmod(0.123456, 1.23456), fmod(0.123456, 1.23456),
                           CH_EPS);
  ck_assert_ldouble_nan(fmod(LDBL_MAX, DBL_MAX));
  for (double i = -10.0001; i <= 10.0; i += 0.5) {
    ck_assert_ldouble_eq_tol(fmod(i, 1.00003), fmod(i, 1.00003), CH_EPS);
  }
}
END_TEST

START_TEST(test_pow) {
  ck_assert_ldouble_eq_tol(pow(0.923456, 5000), pow(0.923456, 5000),
                           CH_EPS);

  ck_assert_ldouble_eq_tol(pow(-0.1, 2), pow(-0.1, 2), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(0.8, 3), pow(0.8, 3), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(-5.5, 1), pow(-5.5, 1), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(1, 1), pow(1, 1), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(0, 1), fmod(0, 1), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(1, 0), pow(1, 0), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(0, 0), pow(0, 0), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(-0, 0), pow(-0, 0), CH_EPS);

  ck_assert_ldouble_eq_tol(pow(10, 5), pow(10, 5), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(5, 0), pow(5, 0), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(0, 5), pow(0, 5), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(5, 0.5), pow(5, 0.5), CH_EPS);

  ck_assert_ldouble_nan(pow(-5, 0.5));
  ck_assert_ldouble_nan(pow(-5, -0.5));
  ck_assert_ldouble_nan(pow(-5.5, 0.5));

  ck_assert_ldouble_eq_tol(pow(5.5, 5), pow(5.5, 5), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(5.5, -5), pow(5.5, -5), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(-5.5, -5), pow(-5.5, -5), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(5.5, 5.5), pow(5.5, 5.5), CH_EPS);

  ck_assert_double_eq(pow(CH_INF, 0), pow(CH_INF, 0));
  ck_assert_double_eq(pow(CH_INF, -1), pow(CH_INF, -1));
  ck_assert_double_eq(pow(-1, -CH_INF), pow(-1, -CH_INF));
  ck_assert_double_eq(pow(0, CH_INF), pow(0, CH_INF));
  ck_assert_double_eq(pow(-0, -CH_INF), pow(-0, -CH_INF));

  ck_assert_double_nan(pow(0, CH_NAN));
  ck_assert_double_eq(pow(NAN, 0), pow(CH_NAN, 0));
  ck_assert_double_nan(pow(CH_NAN, CH_NAN));

  ck_assert_double_eq(pow(CH_INF, CH_INF), pow(CH_INF, CH_INF));
  ck_assert_double_eq(pow(CH_INF, -CH_INF), pow(CH_INF, -CH_INF));
  ck_assert_double_eq(pow(-CH_INF, CH_INF), pow(-CH_INF, CH_INF));
  ck_assert_double_eq(pow(-CH_INF, -CH_INF), pow(-CH_INF, -CH_INF));
  ck_assert_double_eq(pow(-1, CH_INF), pow(-1, CH_INF));
  ck_assert_double_eq(pow(1, -CH_INF), pow(1, -CH_INF));
  ck_assert_double_eq(pow(1, CH_INF), pow(1, CH_INF));
  ck_assert_double_eq(pow(1, NAN), pow(1, CH_NAN));

  ck_assert_double_nan(pow(CH_NAN, CH_INF));
  ck_assert_double_nan(pow(CH_INF, CH_NAN));
  ck_assert_double_nan(pow(CH_NAN, -CH_INF));
  ck_assert_double_nan(pow(-CH_INF, CH_NAN));

  ck_assert_double_eq(pow(2, CH_INF), pow(2, CH_INF));
  ck_assert_double_eq(pow(0.5, CH_INF), pow(0.5, CH_INF));
  ck_assert_double_eq(pow(-2, CH_INF), pow(-2, CH_INF));
  ck_assert_double_eq(pow(2, -CH_INF), pow(2, -CH_INF));
  ck_assert_double_eq(pow(0.5, -CH_INF), pow(0.5, -CH_INF));
  ck_assert_double_eq(pow(-2, -CH_INF), pow(-2, -CH_INF));

  for (double i = 0.00001; i <= 10.0; i += 0.5) {
    ck_assert_ldouble_eq_tol(pow(i, i), pow(i, i), DBL_MAX / pow(10, 16));
  }

  ck_assert_ldouble_eq_tol(pow(-1, 15), pow(-1, 15), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(-1, 16), pow(-1, 16), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(-0.1, 15), pow(-0.1, 15), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(-0.1, 16), pow(-0.1, 16), CH_EPS);
  ck_assert_ldouble_eq_tol(pow(-10, 15), pow(-10, 15),
                           DBL_MAX / pow(10, 16));
  ck_assert_ldouble_eq_tol(pow(-10, 16), pow(-10, 16),
                           DBL_MAX / pow(10, 16));
}
END_TEST

START_TEST(test_fabs) {
  ck_assert_ldouble_eq_tol(fabs(10.2), fabs(10.2), CH_EPS);
  ck_assert_ldouble_eq_tol(fabs(-3.45), fabs(-3.45), CH_EPS);
  ck_assert_ldouble_eq_tol(fabs(1.23456789), fabs(1.23456789), CH_EPS);
  ck_assert_ldouble_eq_tol(fabs(-1.23456789), fabs(-1.23456789), CH_EPS);
  ck_assert_ldouble_eq_tol(fabs(-CH_EPS), fabs(-CH_EPS), CH_EPS);
  ck_assert_ldouble_eq(fabs(-CH_INF), fabs(-CH_INF));
  ck_assert_ldouble_eq(fabs(CH_INF), fabs(CH_INF));
  ck_assert_ldouble_nan(fabs(-CH_NAN));
  ck_assert_ldouble_nan(fabs(CH_NAN));
  ck_assert_ldouble_eq_tol(fabs(0.0), fabs(0.0), CH_EPS);
  ck_assert_ldouble_eq_tol(fabs(-0.0), fabs(-0.0), CH_EPS);
  ck_assert_ldouble_eq_tol(fabs(DBL_MIN), fabs(DBL_MIN), CH_EPS);
  ck_assert_ldouble_eq_tol(fabs(DBL_MAX), fabs(DBL_MAX), CH_EPS);
  for (double i = -10.00001; i <= 10.0; i += 0.5) {
    ck_assert_ldouble_eq_tol(fabs(i), fabs(i), CH_EPS);
  }
}
END_TEST

START_TEST(test_floor) {
  ck_assert_ldouble_eq_tol(floor(1.6666666), floor(1.66666666), CH_EPS);
  ck_assert_ldouble_eq_tol(floor(-123.45678), floor(-123.45678), CH_EPS);
  ck_assert_ldouble_eq_tol(floor(3.45), floor(3.45), CH_EPS);
  ck_assert_ldouble_eq_tol(floor(5), floor(5), CH_EPS);
  ck_assert_ldouble_eq_tol(floor(0), floor(0), CH_EPS);
  ck_assert_ldouble_eq_tol(floor(0.555553499), floor(0.555553499), CH_EPS);
  ck_assert_ldouble_eq_tol(floor(-0.1), floor(-0.1), CH_EPS);
  ck_assert_ldouble_eq(floor(CH_INF), floor(CH_INF));
  ck_assert_ldouble_eq(floor(-CH_INF), floor(-CH_INF));
  ck_assert_ldouble_nan(floor(CH_NAN));
  ck_assert_ldouble_nan(floor(-CH_NAN));
  ck_assert_ldouble_eq_tol(floor(DBL_MIN), floor(DBL_MIN), CH_EPS);
  for (double i = -10.00001; i <= 10.0; i += 0.5) {
    ck_assert_ldouble_eq_tol(floor(i), floor(i), CH_EPS);
  }
}
END_TEST

START_TEST(test_ceil) {
  ck_assert_ldouble_eq_tol(ceil(1.6666666), ceil(1.66666666), CH_EPS);
  ck_assert_ldouble_eq_tol(ceil(-123.45678), ceil(-123.45678), CH_EPS);
  ck_assert_ldouble_eq_tol(ceil(3.45), ceil(3.45), CH_EPS);
  ck_assert_ldouble_eq_tol(ceil(5), ceil(5), CH_EPS);
  ck_assert_ldouble_eq_tol(ceil(0.555553499), ceil(0.555553499), CH_EPS);
  ck_assert_ldouble_eq_tol(ceil(0), ceil(0), CH_EPS);
  ck_assert_ldouble_eq(ceil(CH_INF), ceil(CH_INF));
  ck_assert_ldouble_eq(ceil(-CH_INF), ceil(-CH_INF));
  ck_assert_ldouble_nan(ceil(CH_NAN));
  ck_assert_ldouble_nan(ceil(-CH_NAN));
  ck_assert_ldouble_eq(ceil(DBL_MIN), 0);
  for (double i = -10.00001; i <= 10.0; i += 0.5) {
    ck_assert_ldouble_eq_tol(ceil(i), ceil(i), CH_EPS);
  }
}
END_TEST

START_TEST(test_sqrt) {
  ck_assert_ldouble_eq_tol(sqrt(0), sqrt(0), CH_EPS);
  ck_assert_ldouble_eq_tol(sqrt(-0), sqrt(-0), CH_EPS);
  ck_assert_ldouble_eq_tol(sqrt(1), sqrt(1), CH_EPS);
  ck_assert_ldouble_eq_tol(sqrt(2), sqrt(2), CH_EPS);
  ck_assert_ldouble_eq_tol(sqrt(4), sqrt(4), CH_EPS);

  ck_assert_ldouble_eq_tol(sqrt(123456.789123), sqrt(123456.789123),
                           CH_EPS);
  ck_assert_ldouble_eq_tol(sqrt(CH_EPS), sqrt(CH_EPS), CH_EPS);

  ck_assert_ldouble_nan(sqrt(-1));
  ck_assert_ldouble_nan(sqrt(-0.9));
  ck_assert_ldouble_nan(sqrt(-CH_EPS));

  ck_assert_ldouble_eq(sqrt(CH_INF), sqrt(CH_INF));

  ck_assert_ldouble_nan(sqrt(-CH_NAN));
  ck_assert_ldouble_nan(sqrt(CH_NAN));

  for (double i = 0.00001; i <= 10.0; i += 0.5) {
    ck_assert_ldouble_eq_tol(sqrt(i), sqrt(i), CH_EPS);
  }
}
END_TEST

START_TEST(test_log) {
  ck_assert_ldouble_eq(log(0), log(0));
  ck_assert_ldouble_eq(log(-0), log(-0));

  ck_assert_ldouble_eq_tol(log(1), log(1), CH_EPS);
  ck_assert_ldouble_eq_tol(log(CH_EXP), log(CH_EXP), CH_EPS);
  ck_assert_ldouble_eq_tol(log(0.5 * CH_EXP), log(0.5 * CH_EXP), CH_EPS);
  ck_assert_ldouble_eq_tol(log(5 * CH_EXP), log(5 * CH_EXP), CH_EPS);
  ck_assert_ldouble_eq_tol(log(5.5), log(5.5), CH_EPS);

  ck_assert_ldouble_nan(log(-1));
  ck_assert_ldouble_nan(log(-0.1));
  ck_assert_ldouble_nan(log(-CH_EPS));
  ck_assert_ldouble_nan(log(-CH_INF));
  ck_assert_ldouble_nan(log(-CH_NAN));
  ck_assert_ldouble_nan(log(CH_NAN));

  ck_assert_ldouble_eq(log(CH_INF), log(CH_INF));

  ck_assert_ldouble_eq_tol(log(DBL_MAX), log(DBL_MAX), CH_EPS);

  for (double i = 1.00001; i <= 10; i += 0.5) {
    ck_assert_ldouble_eq_tol(log(i), log(i), CH_EPS);
  }
}
END_TEST

START_TEST(test_exp) {
  ck_assert_ldouble_eq_tol(exp(0), exp(0), CH_EPS);
  ck_assert_ldouble_eq_tol(exp(-0), exp(-0), CH_EPS);
  ck_assert_ldouble_eq_tol(exp(1), exp(1), CH_EPS);
  ck_assert_ldouble_eq_tol(exp(-1), exp(-1), CH_EPS);

  ck_assert_ldouble_eq_tol(exp(2.7), exp(2.7), CH_EPS);
  ck_assert_ldouble_eq_tol(exp(100), exp(100), DBL_MAX / pow(10, 16));
  ck_assert_ldouble_eq_tol(exp(-1000), exp(-1000), CH_EPS);

  ck_assert_ldouble_infinite(exp(1000));
  ck_assert_ldouble_infinite(exp(CH_INF));
  ck_assert_ldouble_eq_tol(exp(-CH_INF), exp(-CH_INF), CH_EPS);
  ck_assert_ldouble_nan(exp(-CH_NAN));
  ck_assert_ldouble_nan(exp(CH_NAN));

  ck_assert_ldouble_eq_tol(exp(1.23456789), exp(1.23456789), CH_EPS);
  ck_assert_ldouble_eq_tol(exp(-1.23456789), exp(-1.23456789), CH_EPS);
  ck_assert_ldouble_eq_tol(exp(500), exp(500), DBL_MAX / pow(10, 16));
  ck_assert_ldouble_eq_tol(exp(-500), exp(-500), CH_EPS);

  ck_assert_ldouble_infinite(exp(DBL_MAX));

  for (double i = -10.00001; i <= 10.0; i += 0.5)
    ck_assert_ldouble_eq_tol(exp(i), exp(i), CH_EPS);
}
END_TEST

START_TEST(test_sin) {
  ck_assert_ldouble_eq_tol(sin(0.8), sin(0.8), CH_EPS);
  ck_assert_ldouble_eq_tol(sin(-0.8), sin(-0.8), CH_EPS);

  ck_assert_ldouble_eq_tol(sin(0), sin(0), CH_EPS);
  ck_assert_ldouble_eq_tol(sin(1), sin(1), CH_EPS);
  ck_assert_ldouble_eq_tol(sin(-1), sin(-1), CH_EPS);

  ck_assert_ldouble_eq_tol(sin(100000000.0), sin(100000000.0), CH_EPS);
  ck_assert_ldouble_eq_tol(sin(-100000000.0), sin(-100000000.0), CH_EPS);
  ck_assert_ldouble_eq_tol(sin(0.923456), sin(0.923456), CH_EPS);

  ck_assert_ldouble_nan(sin(CH_NAN));
  ck_assert_ldouble_nan(sin(CH_INF));
  ck_assert_ldouble_nan(sin(-CH_INF));

  ck_assert_ldouble_eq_tol(sin(CH_PI), sin(CH_PI), CH_EPS);
  ck_assert_ldouble_eq_tol(sin(-CH_PI), sin(-CH_PI), CH_EPS);
  ck_assert_ldouble_eq_tol(sin(2 * CH_PI), sin(2 * CH_PI), CH_EPS);
  ck_assert_ldouble_eq_tol(sin(-2 * CH_PI), sin(-2 * CH_PI), CH_EPS);

  for (double i = -4.00001; i <= 4.0; i += 0.5) {
    ck_assert_ldouble_eq_tol(sin(i), sin(i), CH_EPS);
  }
}
END_TEST

START_TEST(test_cos) {
  ck_assert_ldouble_eq_tol(cos(0.8), cos(0.8), CH_EPS);
  ck_assert_ldouble_eq_tol(cos(-0.8), cos(-0.8), CH_EPS);

  ck_assert_ldouble_eq_tol(cos(0), cos(0), CH_EPS);
  ck_assert_ldouble_eq_tol(cos(1), cos(1), CH_EPS);
  ck_assert_ldouble_eq_tol(cos(-1), cos(-1), CH_EPS);

  ck_assert_ldouble_eq_tol(cos(100000000.0), cos(100000000.0), CH_EPS);
  ck_assert_ldouble_eq_tol(cos(-100000000.0), cos(-100000000.0), CH_EPS);
  ck_assert_ldouble_eq_tol(cos(0.923456), cos(0.923456), CH_EPS);

  ck_assert_ldouble_nan(cos(CH_NAN));
  ck_assert_ldouble_nan(cos(CH_INF));
  ck_assert_ldouble_nan(cos(-CH_INF));

  ck_assert_ldouble_eq_tol(cos(CH_PI), cos(CH_PI), CH_EPS);
  ck_assert_ldouble_eq_tol(cos(-CH_PI), cos(-CH_PI), CH_EPS);
  ck_assert_ldouble_eq_tol(cos(2 * CH_PI), cos(2 * CH_PI), CH_EPS);
  ck_assert_ldouble_eq_tol(cos(-2 * CH_PI), cos(-2 * CH_PI), CH_EPS);

  for (double i = -4.00001; i <= 4.0; i += 0.5) {
    ck_assert_ldouble_eq_tol(cos(i), cos(i), CH_EPS);
  }
}
END_TEST

START_TEST(test_tan) {
  ck_assert_ldouble_eq_tol(tan(0.8), tan(0.8), CH_EPS);
  ck_assert_ldouble_eq_tol(tan(-0.8), tan(-0.8), CH_EPS);

  ck_assert_ldouble_eq_tol(tan(0), tan(0), CH_EPS);
  ck_assert_ldouble_eq_tol(tan(1), tan(1), CH_EPS);
  ck_assert_ldouble_eq_tol(tan(-1), tan(-1), CH_EPS);

  ck_assert_ldouble_eq_tol(tan(100000000.0), tan(100000000.0), CH_EPS);
  ck_assert_ldouble_eq_tol(tan(-100000000.0), tan(-100000000.0), CH_EPS);
  ck_assert_ldouble_eq_tol(tan(0.923456), tan(0.923456), CH_EPS);

  ck_assert_ldouble_nan(tan(CH_NAN));
  ck_assert_ldouble_nan(tan(CH_INF));
  ck_assert_ldouble_nan(tan(-CH_INF));

  ck_assert_ldouble_eq_tol(tan(CH_PI), tan(CH_PI), CH_EPS);
  ck_assert_ldouble_eq_tol(tan(-CH_PI), tan(-CH_PI), CH_EPS);
  ck_assert_ldouble_eq_tol(tan(2 * CH_PI), tan(2 * CH_PI), CH_EPS);
  ck_assert_ldouble_eq_tol(tan(-2 * CH_PI), tan(-2 * CH_PI), CH_EPS);

  for (double i = -1.00001; i <= 1; i += 0.1) {
    ck_assert_ldouble_eq_tol(tan(i), tan(i), CH_EPS);
  }
}
END_TEST

START_TEST(test_asin) {
  ck_assert_ldouble_eq_tol(asin(0.8), asin(0.8), CH_EPS);
  ck_assert_ldouble_eq_tol(asin(-0.8), asin(-0.8), CH_EPS);

  ck_assert_ldouble_eq_tol(asin(0), asin(0), CH_EPS);
  ck_assert_ldouble_eq_tol(asin(1), asin(1), CH_EPS);
  ck_assert_ldouble_eq_tol(asin(-1), asin(-1), CH_EPS);

  ck_assert_ldouble_nan(asin(100000000.0));
  ck_assert_ldouble_nan(asin(-1000000000000000));

  ck_assert_ldouble_eq_tol(asin(0.923456), asin(0.923456), CH_EPS);

  ck_assert_ldouble_nan(asin(CH_NAN));
  ck_assert_ldouble_nan(asin(CH_INF));
  ck_assert_ldouble_nan(asin(-CH_INF));

  ck_assert_ldouble_eq_tol(asin(0.70710678), asin(0.70710678), CH_EPS);
  ck_assert_ldouble_eq_tol(asin(-0.70710678), asin(-0.70710678), CH_EPS);

  for (double i = -0.99999; i <= 0.99; i += 0.1) {
    ck_assert_ldouble_eq_tol(asin(i), asin(i), CH_EPS);
  }
}
END_TEST

START_TEST(test_acos) {
  ck_assert_ldouble_eq_tol(acos(0.8), acos(0.8), CH_EPS);
  ck_assert_ldouble_eq_tol(acos(-0.8), acos(-0.8), CH_EPS);

  ck_assert_ldouble_eq_tol(acos(0), acos(0), CH_EPS);
  ck_assert_ldouble_eq_tol(acos(1), acos(1), CH_EPS);
  ck_assert_ldouble_eq_tol(acos(-1), acos(-1), CH_EPS);

  ck_assert_ldouble_nan(acos(100000000.0));
  ck_assert_ldouble_nan(acos(-1000000000000000));

  ck_assert_ldouble_eq_tol(acos(0.923456), acos(0.923456), CH_EPS);

  ck_assert_ldouble_nan(acos(CH_NAN));
  ck_assert_ldouble_nan(acos(CH_INF));
  ck_assert_ldouble_nan(acos(-CH_INF));

  ck_assert_ldouble_eq_tol(acos(0.70710678), acos(0.70710678), CH_EPS);
  ck_assert_ldouble_eq_tol(acos(-0.70710678), acos(-0.70710678), CH_EPS);

  for (double i = -0.99999; i <= 0.99; i += 0.1) {
    ck_assert_ldouble_eq_tol(acos(i), acos(i), CH_EPS);
  }
}
END_TEST

START_TEST(test_atan) {
  ck_assert_ldouble_eq_tol(atan(0.1), atan(0.1), CH_EPS);
  ck_assert_ldouble_eq_tol(atan(-0.1), atan(-0.1), CH_EPS);
  ck_assert_ldouble_eq_tol(atan(0.3), atan(0.3), CH_EPS);
  ck_assert_ldouble_eq_tol(atan(-0.3), atan(-0.3), CH_EPS);
  ck_assert_ldouble_eq_tol(atan(0.5), atan(0.5), CH_EPS);
  ck_assert_ldouble_eq_tol(atan(-0.5), atan(-0.5), CH_EPS);
  ck_assert_ldouble_eq_tol(atan(0), atan(0), CH_EPS);
  ck_assert_ldouble_eq_tol(atan(1), atan(1), CH_EPS);
  ck_assert_ldouble_eq_tol(atan(-1), atan(-1), CH_EPS);
  ck_assert_ldouble_eq_tol(atan(2), atan(2), CH_EPS);
  ck_assert_ldouble_eq_tol(atan(100000000.0), atan(100000000.0), CH_EPS);
  ck_assert_ldouble_eq_tol(atan(-1000000000000000), atan(-1000000000000000),
                           CH_EPS);

  ck_assert_ldouble_eq_tol(atan(0.9234560), atan(0.923456), CH_EPS);

  ck_assert_ldouble_nan(atan(CH_NAN));
  ck_assert_ldouble_eq_tol(atan(CH_INF), atan(CH_INF), CH_EPS);
  ck_assert_ldouble_eq_tol(atan(-CH_INF), atan(-CH_INF), CH_EPS);

  for (double i = -5.00001; i <= -1.01; i += 0.5) {
    ck_assert_ldouble_eq_tol(atan(i), atan(i), CH_EPS);
  }
  for (double i = 1.01; i <= 5.00001; i += 0.5) {
    ck_assert_ldouble_eq_tol(atan(i), atan(i), CH_EPS);
  }
}
END_TEST

Suite *math_suite(void) {
  Suite *s = suite_create("math_testcase");
  TCase *tc_math = tcase_create("Core");

  tcase_add_test(tc_math, test_abs);
  tcase_add_test(tc_math, test_fmod);
  tcase_add_test(tc_math, test_sqrt);
  tcase_add_test(tc_math, test_fabs);
  tcase_add_test(tc_math, test_floor);
  tcase_add_test(tc_math, test_ceil);
  tcase_add_test(tc_math, test_exp);
  tcase_add_test(tc_math, test_sin);
  tcase_add_test(tc_math, test_cos);
  tcase_add_test(tc_math, test_tan);
  tcase_add_test(tc_math, test_pow);
  tcase_add_test(tc_math, test_log);
  tcase_add_test(tc_math, test_atan);
  tcase_add_test(tc_math, test_acos);
  tcase_add_test(tc_math, test_asin);

  suite_add_tcase(s, tc_math);

  return s;
}

int main() {
  int nf;
  Suite *s;
  SRunner *sr;

  s = math_suite();
  sr = srunner_create(s);

  srunner_run_all(sr, CK_NORMAL);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);
  return (nf == 0) ? EXIT_SUCCESS : EXIT_FAILURE;
}
